import { TABS } from '@app/shared/constants/tab-keys';

export const MODULE_PATHS = {

/*ASSEMBLY*/

    //ado
    APP_ASSY_ADO_VEHICLEDETAILS: 'app/main/assy/andon/vehicledetails/vehicledetails.module',
    APP_ASSY_ADO_TOTALDELAYFINALASAKAI: 'app/main/assy/andon/totaldelayfinalasakai/totaldelayfinalasakai.module',
    APP_ASSY_ADO_AINPLAN: 'app/main/assy/andon/ainplan/ainplan.module',
    APP_ASSY_ADO_APLANSHIFTBASE: 'app/main/assy/andon/aplanshiftbase/aplanshiftbase.module',
    APP_ASSY_ADO_ASSEMBLYDATA: 'app/main/assy/andon/assemblydata/assemblydata.module',

/*FRAME */
    APP_FRM_ADO_FRAMEPLAN: 'app/main/frame/andon/frameplan/frameplan.module',
    APP_FRM_ADO_FRAMEPROGRESS: 'app/main/frame/andon/frameprogress/frameprogress.module',
    APP_FRM_ADO_FRAMEPLANA1: 'app/main/frame/andon/frameplana1/frameplana1.module',
    APP_FRM_ADO_FRAMEPLANBMPV: 'app/main/frame/andon/frameplanbmpv/frameplanbmpv.module',


/* MASTER */
    /* MASTER - Working Pattern */
    APP_MASTER_WORKING_PATTERN_SHOP: 'app/main/master/workingpattern/shop/shop.module',
    APP_MASTER_WORKING_PATTERN_CALENDAR: 'app/main/master/workingpattern/calendar/calendar.module',
    APP_MASTER_WORKING_PATTERN_SEASONMONTH: 'app/main/master/workingpattern/seasonmonth/seasonmonth.module',
    APP_MASTER_WORKING_PATTERN_PATTERNH: 'app/main/master/workingpattern/patternh/patternh.module',
    APP_MASTER_WORKING_PATTERN_WORKINGTIME: 'app/main/master/workingpattern/workingtime/workingtime.module',
    APP_MASTER_WORKING_PATTERN_WORKINGTYPE: 'app/main/master/workingpattern/workingtype/workingtype.module',
    APP_MASTER_WORKING_PATTERN_DAILYWORKINGTIME: 'app/main/master/workingpattern/dailyworkingtime/dailyworkingtime.module',
    APP_MASTER_WORKING_PATTERN_PATTERND: 'app/main/master/workingpattern/patternd/patternd.module',
    APP_MASTER_WORKING_PATTERN_WEEK: 'app/main/master/workingpattern/week/week.module',

    // MASTER - Welding
    APP_MASTER_WELDING_PROCESS: 'app/main/master/welding/process/process.module',

    /* MASTER - Common*/

    APP_MASTER_COMMON_LOOKUP: 'app/main/master/common/lookup/lookup.module',
    APP_MASTER_COMMON_TAKTTIME: 'app/main/master/common/takttime/takttime.module',
    APP_MASTER_COMMON_MODEL: 'app/main/master/common/model/model.module',
    APP_MASTER_COMMON_COLOR : 'app/main/master/common/color/color.module',
    APP_MASTER_COMMON_LOOKUP2: 'app/main/master/common2/lookup2.module',


    // MASTER - LogA
    APP_MASTER_LOGA_PLCSIGNAL: 'app/main/master/loga/plcsignal/plcsignal.module',
    APP_MASTER_LOGA_TRIP: 'app/main/master/loga/trip/trip.module',
    APP_MASTER_LOGA_BP2PARTLIST: 'app/main/master/loga/bp2partlist/bp2partlist.module',
    APP_MASTER_LOGA_BP2PROCESS: 'app/main/master/loga/bp2process/bp2process.module',
    APP_MASTER_LOGA_BP2ECAR: 'app/main/master/loga/bp2ecar/bp2ecar.module',
    APP_MASTER_LOGA_BP2PARTLISTGRADE: 'app/main/master/loga/bp2partlistgrade/bp2partlistgrade.module',
    APP_MASTER_LOGA_EKBPARTLIST: 'app/main/master/loga/ekbpartlist/ekbpartlist.module',
    APP_MASTER_LOGA_EKBPARTLISTGRADE: 'app/main/master/loga/ekbpartlistgrade/ekbpartlistgrade.module',
    APP_MASTER_LOGA_EKBPROCESS: 'app/main/master/loga/ekbprocess/ekbprocess.module',
    APP_MASTER_LOGA_EKBUSER: 'app/main/master/loga/ekbuser/ekbuser.module',
    APP_MASTER_LOGA_BARPROCESS: 'app/main/master/loga/barprocess/barprocess.module',
    APP_MASTER_LOGA_BARUSER: 'app/main/master/loga/baruser/baruser.module',
    APP_MASTER_LOGA_SPSRACK: 'app/main/master/loga/spsrack/spsrack.module',
    APP_MASTER_LOGA_PCRACK: 'app/main/master/loga/pcrack/pcrack.module',

    //MASTER - Painting
    APP_MASTER_PAINTING_PAINTINGPROCESS: 'app/main/master/painting/paintingprocess/paintingprocess.module',
    APP_MASTER_PAINTING_BMPPARTLIST: 'app/main/master/painting/bmppartlist/bmppartlist.module',
    APP_MASTER_PAINTING_BMPPARTTYPE: 'app/main/master/painting/bmpparttype/bmpparttype.module',
    APP_MASTER_PAINTING_INVENTORYSTD: 'app/main/master/painting/inventorystd/inventorystd.module',

    APP_MASTER_FRAME_PROCESS: 'app/main/master/frame/process/process.module',

    // MASTER - LogW
    APP_MASTER_LOGW_ECIPART: 'app/main/master/logw/ecipart/ecipart.module',
    APP_MASTER_LOGW_ECIPARTMODULE: 'app/main/master/logw/ecipartmodule/ecipartmodule.module',
    APP_MASTER_LOGW_CONTDEVANNINGLT: 'app/main/master/logw/contdevanninglt/contdevanninglt.module',
    APP_MASTER_LOGW_MODELGRADE: 'app/main/master/logw/modelgrade/modelgrade.module',
    APP_MASTER_LOGW_RENBANMODULE: 'app/main/master/logw/renbanmodule/renbanmodule.module',
    APP_MASTER_LOGW_LAYOUTSETUP: 'app/main/master/logw/layoutsetup/layoutsetup.module',
    APP_MASTER_LOGW_LAYOUT: 'app/main/master/logw/layout/layout.module',
    APP_MASTER_LOGW_PLCSIGNAL: 'app/main/master/logw/plcsignal/plcsignal.module',
    // MASTER - RobbingLane
    APP_MASTER_LOGW_ROBBINGLANE: 'app/main/master/logw/robbinglane/robbinglane.module',
    APP_MASTER_LOGW_SCREENCONFIG: 'app/main/master/logw/screenconfig/screenconfig.module',

    // MASTER - PickingTablet
    APP_MASTER_LOGW_PICKINGTABLET: 'app/main/master/logw/pickingtablet/pickingtablet.module',
    APP_MASTER_LOGW_PICKINGTABLETSETUP: 'app/main/master/logw/pickingtabletsetup/pickingtabletsetup.module',

    // MASTER - unpackingpart
    APP_MASTER_LOGW_UNPACKINGPART: 'app/main/master/logw/unpackingpart/unpackingpart.module',

    //CallingTight
    APP_MASTER_LOGW_CALLINGLIGHT: 'app/main/master/logw/callinglight/callinglight.module',

    /* INV */
    //Inv_D125
    APP_INV_D125_STOCK: 'app/main/inv/d125/stock/stock.module',
    APP_INV_D125_INVOUTLINEOFF: 'app/main/inv/d125/invoutlineoff/invoutlineoff.module',
    APP_INV_D125_OUTWIPSTOCK: 'app/main/inv/d125/outwipstock/outwipstock.module',
    APP_INV_D125_INDETAILS: 'app/main/inv/d125/indetails/indetails.module',

    //APP_Inv_Dmr
    APP_INV_DMR_IMPORTBYCONT: 'app/main/inv/dmr/importbycont/importbycont.module',

    //APP_Inv_Proc
    APP_INV_PROC_PRODUCTIONMAPPING: 'app/main/inv/proc/invproductionmapping/invproductionmapping.module',

/* INVENTORY */
    APP_INVENTORY_CKD_STOCKPART: 'app/main/inventory/ckd/stock-part/stock-part.module',
    APP_INVENTORY_CKD_STOCKISSUSING: 'app/main/inventory/ckd/stock-issuing/stock-issuing.module',
    APP_INVENTORY_CKD_STOCKRECEIVING: 'app/main/inventory/ckd/stock-receiving/stock-receiving.module',
    APP_INVENTORY_CKD_STOCKBALANCE: 'app/main/inventory/ckd/stock-balance/stock-balance.module',

    APP_INVENTORY_CKD_PHYSICALSTOCKPART: 'app/main/inventory/ckd/physical-stock-part/physical-stock-part.module',
    APP_INVENTORY_CKD_PHYSICALSTOCKRECEIVING: 'app/main/inventory/ckd/physical-stock-receiving/physical-stock-receiving.module',
    APP_INVENTORY_CKD_PHYSICALSTOCKISSUING: 'app/main/inventory/ckd/physical-stock-issuing/physical-stock-issuing.module',
    APP_INVENTORY_CKD_PHYSICALSTOCKPERIOD: 'app/main/inventory/ckd/physical-stock-period/physical-stock-period.module',

/*LogA */
    APP_LOGA_LDS_LOTPLAN: 'app/main/loga/lds/lotplan/lotplan.module',
    APP_LOGA_LDS_LOTDIRECTSUPPLYANDONA1: '/screens/lotdirectsupplyandon.module',
    APP_LOGA_LDS_LOTDIRECTSUPPLYANDONA2: '/screens/lotdirectsupplyandon.module',
    APP_LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA1 : '/screens/jiririkokuscreen.module',
    APP_LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA2 : '/screens/jiririkokuscreen.module',

    APP_LOGA_BP2_PROGRESS: 'app/main/loga/bp2/progress/progress.module',
    APP_LOGA_BP2_PXPUPPLAN: 'app/main/loga/bp2/pxpupplan/pxpupplan.module',

    APP_LOGA_BP2_BIGPARTPXPUP: '/screens/bigpartpxpup.module',

    // new
    APP_LOGA_BP2_BIGPARTJIRIRIKOKUA1NEW: '/screens/LgaBp2ProgressMonitorScreen.module',
    APP_LOGA_BP2_BIGPARTJIRIRIKOKUA2NEW: '/screens/LgaBp2ProgressMonitorScreen.module',

    APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1NEW: '/screens/LgaBp2ProgressScreen.module',
    APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2NEW: '/screens/LgaBp2ProgressScreen.module',

    APP_LOGA_BP2_BIGPARTJIRIRIKOKUA1: '/screens/bigpartjiririkokuscreen.module',
    APP_LOGA_BP2_BIGPARTJIRIRIKOKUA2: '/screens/bigpartjiririkokuscreen.module',

    APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1: '/screens/bigpartdirectdeliveryprogressandon.module',
    APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2: '/screens/bigpartdirectdeliveryprogressandon.module',

    APP_LOGA_BP2_BIGPARTTABLETA1: '/screens/bigparttablet2.module',
    APP_LOGA_BP2_BIGPARTTABLETA2: '/screens/bigparttablet2.module',

    APP_LOGA_EKB_PROGRESSSCREEN: '/screens/progressscreen.module',
    APP_LOGA_EKB_PROGRESS: 'app/main/loga/ekb/progress/progress.module',
    APP_LOGA_EKB_PROGRESSDETAILS: 'app/main/loga/ekb/progressdetails/progressdetails.module',
    APP_LOGA_EKB_EKANBAN: 'app/main/loga/ekb/ekanban/ekanban.module',
    APP_LOGA_EKB_EKANBANPROGRESSSCREENA1: '/screens/ekanbanprogressscreen.module',
    APP_LOGA_EKB_EKANBANPROGRESSSCREENA2: '/screens/ekanbanprogressscreen.module',

    APP_LOGA_BARSCANINFO: 'app/main/loga/bar/barscaninfo/barscaninfo.module',
    APP_LOGA_PCS_STOCK: 'app/main/loga/pcs/stock/stock.module',

    APP_LOGA_SPS_STOCK: 'app/main/loga/sps/stock/stock.module',



    //Lgw Mwh
        APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTSTATUS: 'app/main/logw/ado/callinglight/callinglightstatus.module',
        APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTW1: '/screens/callinglight.module',
        APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTW2: '/screens/callinglight.module',
        APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTW3: '/screens/callinglight.module',
        APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTIP: '/screens/callinglight.module',

        APP_LGW_MWH_LOGW_MWH_MWHSMALLPART: '/screens/pxpsmallpartinput.module',
        APP_LGW_MWH_LOGW_MWH_MWHBIGPART: '/screens/pxpbigpartinput.module',
        APP_LGW_MWH_LOGW_MWH_STOCKATWH: '/screens/stockatwh.module',
        // APP_LGW_MWH_LOGW_MWH_MODULECALLING: 'app/main/logw/mwh/modulecalling/modulecalling.module',
        APP_LGW_MWH_LOGW_MWH_ROBBINGLANE: 'app/main/logw/mwh/robbinglane.module',
        APP_LGW_MWH_LOGW_MWH_CASEDATA: 'app/main/logw/mwh/casedata/casedata.module',
        APP_LGW_MWH_LOGW_MWH_CONTLIST: 'app/main/logw/mwh/contlist/contlist.module',
        APP_LGW_MWH_LOGW_MWH_PARTDATA: 'app/main/logw/mwh/partdata/partdata.module',

        APP_LGW_MWH_LOGW_PUP_LOTUNPACKINGW1: '/screens/lotupackingandon.module',
        APP_LGW_MWH_LOGW_PUP_LOTUNPACKINGW2: '/screens/lotupackingandon.module',
        APP_LGW_MWH_LOGW_PUP_LOTUNPACKINGW3: '/screens/lotupackingandon.module',

        APP_LGW_MWH_LOGW_LUP_LOTUPPLAN: 'app/main/logw/lup/lotupplan/lotupplan.module',
        APP_LGW_MWH_LOGW_LUP_CONTMODULE: 'app/main/logw/lup/contmodule/contmodule.module',
        APP_LGW_MWH_LOGW_PUP_LOTMAKINGTABLET: '/screens/lotmakingtablet.module',

        APP_LGW_MWH_LOGW_DVN_CONTLIST: 'app/main/logw/dvn/contlist/contlist.module',
        APP_LGW_MWH_LOGW_DVN_DEVANNINGSCREEN: '/screens/devanningscreen.module',

        APP_LGW_MWH_LOGW_PUP_PXPUPPLAN: 'app/main/logw/pup/pxpupplan/pxpupplan.module',
        APP_LGW_MWH_LOGW_PUP_MODULEUNPACKINGANDON: '/screens/moduleunpackingandon.module',
        APP_LGW_MWH_LOGW_PUP_PXPUPPLANBASE: 'app/main/logw/pup/pxpupplanbase/pxpupplanbase.module',

        APP_LGW_MWH_LOGW_PIK_PICKINGPROGRESS: 'app/main/logw/pik/pickingprogress/pickingprogress.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGTABLETUBW1: '/screens/pickingtabletandon.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGTABLETSMW1: '/screens/pickingtabletandon.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGTABLETUBW2: '/screens/pickingtabletandon.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGTABLETSMW2: '/screens/pickingtabletandon.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGTABLETUBW3: '/screens/pickingtabletandon.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGTABLETSMW3: '/screens/pickingtabletandon.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGMONITORW1: '/screens/pickingmonitoringscreen.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGMONITORW2: '/screens/pickingmonitoringscreen.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGMONITORW3: '/screens/pickingmonitoringscreen.module',
        APP_LGW_MWH_LOGW_PIK_PICKINGSIGNAL: 'app/main/logw/pik/pickingsignal/pickingsignal.module',

        APP_MST_LOGW_ADO_CALLINGLIGHTSTATUS: 'app/main/master/ado/callinglightstatus/callinglightstatus.module',

    /*Painting Andon*/
        APP_PTA_ADO_CCRMONITOR: '/screens/ccrmonitor.module',
        APP_PTA_ADO_SCANINFO: 'app/main/painting/andon/scaninfo/scaninfo.module',
        APP_PTA_ADO_PAINTINGDATA: 'app/main/painting/andon/paintingdata/paintingdata.module',
        APP_PTA_ADO_PAINTINGPROGRESS: 'app/main/painting/andon/paintingprogress/paintingprogress.module',
        APP_PTA_ADO_LINEEFFICIENCY: 'app/main/painting/andon/lineefficiency/lineefficiency.module',
        APP_PTA_ADO_LINEEFFICIENCYDETAILS: 'app/main/painting/andon/lineefficiencydetails/lineefficiencydetails.module',
        APP_PTA_ADO_LINEREALTIMECONTROL: '/screens/linerealtimecontrols.module',
        APP_PTA_ADO_TOTALDELAY: 'app/main/painting/andon/totaldelay/totaldelay.module',
        APP_PTA_ADO_BUMPER: 'app/main/painting/andon/bumper/bumper.module',
        APP_PTA_ADO_DELAYCONTROLSCREEN: '/screens/delaycontrolscreen.module',
        APP_PTA_ADO_BUMPERCLRINDICATOR: '/screens/bumpergetdataclrindicator.module',
        APP_PTA_ADO_NEXTEDIN: '/screens/nextedin.module',
        APP_PTA_ADO_BUMPERGETDATASMALLSUBASSY: '/screens/bumpergetdatasmallsubassy.module',
        APP_PTA_ADO_BUMPERIN: '/screens/bumperin.module',
        APP_PTA_ADO_BUMPERSUBASSYA1: '/screens/bumpersubassy.module',
        APP_PTA_ADO_BUMPERSUBASSYA2: '/screens/bumpersubassy.module',


    //PLAN
        APP_PLA_CCR_PRODUCTIONPLAN: 'app/main/plan/ccr/productionplan/productionplan.module',

    //Welding Andon
        APP_WEL_ADO_PROCESSINSTRUCTION: '/screens/processinstruction.module',
        APP_WEL_ADO_WELDINGPLAN: 'app/main/welding/andon/weldingplan/weldingplan.module',
        APP_WEL_ADO_WELDINGPROGRESS: 'app/main/welding/andon/weldingprogress/weldingprogress.module',
        APP_WEL_ADO_PUNCHQUEUE: 'app/main/welding/andon/punchqueue/punchqueue.module',
        APP_WEL_ADO_WELDINGSIGNAL: 'app/main/welding/andon/weldingsignal/weldingsignal.module',
        APP_WEL_ADO_PUNCHQUEUEINDICATOR: 'app/main/welding/andon/punchqueueindicator/punchqueueindicator.module',


};


export const MODULE_COMPONENT_MAP = {
/*ASSEMBLY*/
    //sps
    // [MODULE_PATHS.APP_ASSY_SPS_ASSEMBLYDATASCREENA1]: [TABS.ASSY_SPS_ASSEMBLYDATASCREENA1],
    // [MODULE_PATHS.APP_ASSY_SPS_ASSEMBLYDATASCREENA2]: [TABS.ASSY_SPS_ASSEMBLYDATASCREENA2],
    //ado
    [MODULE_PATHS.APP_ASSY_ADO_VEHICLEDETAILS]: [TABS.ASSY_ADO_VEHICLEDETAILS],
    [MODULE_PATHS.APP_ASSY_ADO_TOTALDELAYFINALASAKAI]: [TABS.ASSY_ADO_TOTALDELAYFINALASAKAI],
    [MODULE_PATHS.APP_ASSY_ADO_AINPLAN]: [TABS.ASSY_ADO_AINPLAN],
    [MODULE_PATHS.APP_ASSY_ADO_APLANSHIFTBASE]: [TABS.ASSY_ADO_APLANSHIFTBASE],
    // [MODULE_PATHS.APP_ASSY_ADO_ASSEMBLYDATA]: [TABS.ASSY_ADO_ASSEMBLYDATA],

/*FRAME */
    [MODULE_PATHS.APP_FRM_ADO_FRAMEPLAN]: [TABS.FRM_ADO_FRAMEPLAN],
    [MODULE_PATHS.APP_FRM_ADO_FRAMEPROGRESS]: [TABS.FRM_ADO_FRAMEPROGRESS],
    [MODULE_PATHS.APP_FRM_ADO_FRAMEPLANA1]: [TABS.FRM_ADO_FRAMEPLANA1],
    [MODULE_PATHS.APP_FRM_ADO_FRAMEPLANBMPV]: [TABS.FRM_ADO_FRAMEPLANBMPV],


/* MASTER */
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_SHOP]: [TABS.MASTER_WORKING_PATTERN_SHOP],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_CALENDAR]: [TABS.MASTER_WORKING_PATTERN_CALENDAR],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_SEASONMONTH]: [TABS.MASTER_WORKING_PATTERN_SEASONMONTH],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_PATTERNH]: [TABS.MASTER_WORKING_PATTERN_PATTERNH],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_WORKINGTIME]: [TABS.MASTER_WORKING_PATTERN_WORKINGTIME],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_WORKINGTYPE]: [TABS.MASTER_WORKING_PATTERN_WORKINGTYPE],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_DAILYWORKINGTIME]: [TABS.MASTER_WORKING_PATTERN_DAILYWORKINGTIME],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_PATTERND]: [TABS.MASTER_WORKING_PATTERN_PATTERND],
    [MODULE_PATHS.APP_MASTER_WORKING_PATTERN_WEEK]: [TABS.MASTER_WORKING_PATTERN_WEEK],

    [MODULE_PATHS.APP_MASTER_WELDING_PROCESS]: [TABS.MASTER_WELDING_PROCESS],

    // [MODULE_PATHS.APP_MASTER_COMMON_LOOKUP]: [TABS.MASTER_COMMON_LOOKUP],
    // [MODULE_PATHS.APP_MASTER_COMMON_COLOR]: [TABS.APP_MASTER_COMMON_COLOR],
    // [MODULE_PATHS.APP_MASTER_COMMON_TAKTTIME]: [TABS.APP_MASTER_COMMON_TAKTTIME],
    // [MODULE_PATHS.APP_MASTER_COMMON_MODEL]: [TABS.APP_MASTER_COMMON_MODEL],
    [MODULE_PATHS.APP_MASTER_COMMON_LOOKUP2]: [TABS.MASTER_COMMON_LOOKUP2],


    [MODULE_PATHS.APP_MASTER_LOGA_PLCSIGNAL]: [TABS.MASTER_LOGA_PLCSIGNAL],
    [MODULE_PATHS.APP_MASTER_LOGA_TRIP]: [TABS.MASTER_LOGA_TRIP],
    [MODULE_PATHS.APP_MASTER_LOGA_BP2PARTLIST]: [TABS.MASTER_LOGA_BP2PARTLIST],
    [MODULE_PATHS.APP_MASTER_LOGA_BP2PROCESS]: [TABS.MASTER_LOGA_BP2PROCESS],
    [MODULE_PATHS.APP_MASTER_LOGA_BP2ECAR]: [TABS.MASTER_LOGA_BP2ECAR],
    [MODULE_PATHS.APP_MASTER_LOGA_BP2PARTLISTGRADE]: [TABS.MASTER_LOGA_BP2PARTLISTGRADE],
    [MODULE_PATHS.APP_MASTER_LOGA_EKBPARTLIST]: [TABS.MASTER_LOGA_EKBPARTLIST],
    [MODULE_PATHS.APP_MASTER_LOGA_EKBPARTLISTGRADE]: [TABS.MASTER_LOGA_EKBPARTLISTGRADE],
    [MODULE_PATHS.APP_MASTER_LOGA_EKBPROCESS]: [TABS.MASTER_LOGA_EKBPROCESS],
    [MODULE_PATHS.APP_MASTER_LOGA_EKBUSER]: [TABS.MASTER_LOGA_EKBUSER],
    [MODULE_PATHS.APP_MASTER_LOGA_BARPROCESS]: [TABS.MASTER_LOGA_BARPROCESS],
    [MODULE_PATHS.APP_MASTER_LOGA_BARUSER]: [TABS.MASTER_LOGA_BARUSER],
    [MODULE_PATHS.APP_MASTER_LOGA_SPSRACK]: [TABS.MASTER_LOGA_SPSRACK],
    [MODULE_PATHS.APP_MASTER_LOGA_PCRACK]: [TABS.MASTER_LOGA_PCRACK],

    [MODULE_PATHS.APP_MASTER_PAINTING_PAINTINGPROCESS]: [TABS.MASTER_PAINTING_PAINTINGPROCESS],
    [MODULE_PATHS.APP_MASTER_PAINTING_BMPPARTLIST]: [TABS.MASTER_PAINTING_BMPPARTLIST],
    [MODULE_PATHS.APP_MASTER_PAINTING_BMPPARTTYPE]: [TABS.MASTER_PAINTING_BMPPARTTYPE],
    [MODULE_PATHS.APP_MASTER_PAINTING_INVENTORYSTD]: [TABS.MASTER_PAINTING_INVENTORYSTD],

    [MODULE_PATHS.APP_MASTER_FRAME_PROCESS]: [TABS.MASTER_FRAME_PROCESS],

    [MODULE_PATHS.APP_MASTER_LOGW_ECIPART]: [TABS.MASTER_LOGW_ECIPART],
    [MODULE_PATHS.APP_MASTER_LOGW_ECIPARTMODULE]: [TABS.MASTER_LOGW_ECIPARTMODULE],
    [MODULE_PATHS.APP_MASTER_LOGW_CONTDEVANNINGLT]: [TABS.MASTER_LOGW_CONTDEVANNINGLT],
    [MODULE_PATHS.APP_MASTER_LOGW_MODELGRADE]: [TABS.MASTER_LOGW_MODELGRADE],
    [MODULE_PATHS.APP_MASTER_LOGW_RENBANMODULE]: [TABS.MASTER_LOGW_RENBANMODULE],
    [MODULE_PATHS.APP_MASTER_LOGW_LAYOUTSETUP]: [TABS.MASTER_LOGW_LAYOUTSETUP],
    [MODULE_PATHS.APP_MASTER_LOGW_LAYOUT]: [TABS.MASTER_LOGW_LAYOUT],
    [MODULE_PATHS.APP_MASTER_LOGW_PLCSIGNAL]: [TABS.MASTER_LOGW_PLCSIGNAL],

    [MODULE_PATHS.APP_MASTER_LOGW_ROBBINGLANE]: [TABS.MASTER_LOGW_ROBBINGLANE],
    [MODULE_PATHS.APP_MASTER_LOGW_SCREENCONFIG]: [TABS.MASTER_LOGW_SCREENCONFIG],

    [MODULE_PATHS.APP_MASTER_LOGW_PICKINGTABLET]: [TABS.MASTER_LOGW_PICKINGTABLET],
    [MODULE_PATHS.APP_MASTER_LOGW_PICKINGTABLETSETUP]: [TABS.MASTER_LOGW_PICKINGTABLETSETUP],

    [MODULE_PATHS.APP_MASTER_LOGW_UNPACKINGPART]: [TABS.MASTER_LOGW_UNPACKINGPART],

    [MODULE_PATHS.APP_MASTER_LOGW_CALLINGLIGHT]: [TABS.MASTER_LOGW_CALLINGLIGHT],

/* INV */
    [MODULE_PATHS.APP_INV_D125_STOCK]: [TABS.INV_D125_STOCK],
    [MODULE_PATHS.APP_INV_D125_INVOUTLINEOFF]: [TABS.INV_D125_INVOUTLINEOFF],
    [MODULE_PATHS.APP_INV_D125_OUTWIPSTOCK]: [TABS.INV_D125_OUTWIPSTOCK],
    [MODULE_PATHS.APP_INV_D125_INDETAILS]: [TABS.INV_D125_INDETAILS],

    [MODULE_PATHS.APP_INV_DMR_IMPORTBYCONT]: [TABS.INV_DMR_IMPORTBYCONT],

    [MODULE_PATHS.APP_INV_PROC_PRODUCTIONMAPPING]: [TABS.INV_PROC_PRODUCTIONMAPPING],

    [MODULE_PATHS.APP_LOGA_LDS_LOTPLAN ]: [TABS.LOGA_LDS_LOTPLAN ],
    [MODULE_PATHS.APP_LOGA_LDS_LOTDIRECTSUPPLYANDONA1 ]: [TABS.LOGA_LDS_LOTDIRECTSUPPLYANDONA1 ],
    [MODULE_PATHS.APP_LOGA_LDS_LOTDIRECTSUPPLYANDONA2 ]: [TABS.LOGA_LDS_LOTDIRECTSUPPLYANDONA2 ],
    [MODULE_PATHS.APP_LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA1 ]: [TABS.LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA1 ],
    [MODULE_PATHS.APP_LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA2 ]: [TABS.LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA2 ],

    [MODULE_PATHS.APP_LOGA_BP2_PROGRESS ]: [TABS.LOGA_BP2_PROGRESS ],
    [MODULE_PATHS.APP_LOGA_BP2_PXPUPPLAN ]: [TABS.LOGA_BP2_PXPUPPLAN ],

    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTPXPUP ]: [TABS.LOGA_BP2_BIGPARTPXPUP ],
/* INVENTORY */
    [MODULE_PATHS.APP_INVENTORY_CKD_STOCKPART ]: [TABS.INVENTORY_CKD_STOCKPART ],
    [MODULE_PATHS.APP_INVENTORY_CKD_STOCKISSUSING ]: [TABS.INVENTORY_CKD_STOCKISSUSING ],
    [MODULE_PATHS.APP_INVENTORY_CKD_STOCKRECEIVING ]: [TABS.INVENTORY_CKD_STOCKRECEIVING ],
    [MODULE_PATHS.APP_INVENTORY_CKD_STOCKBALANCE ]: [TABS.INVENTORY_CKD_STOCKBALANCE ],

    [MODULE_PATHS.APP_INVENTORY_CKD_PHYSICALSTOCKPART ]: [TABS.INVENTORY_CKD_PHYSICALSTOCKPART ],
    [MODULE_PATHS.APP_INVENTORY_CKD_PHYSICALSTOCKRECEIVING ]: [TABS.INVENTORY_CKD_PHYSICALSTOCKRECEIVING ],
    [MODULE_PATHS.APP_INVENTORY_CKD_PHYSICALSTOCKISSUING ]: [TABS.INVENTORY_CKD_PHYSICALSTOCKISSUING ],
    [MODULE_PATHS.APP_INVENTORY_CKD_PHYSICALSTOCKPERIOD ]: [TABS.INVENTORY_CKD_PHYSICALSTOCKPERIOD ],

/*LogA */
    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTJIRIRIKOKUA1NEW ]: [TABS.LOGA_BP2_BIGPARTJIRIRIKOKUA1NEW ],
    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTJIRIRIKOKUA2NEW ]: [TABS.LOGA_BP2_BIGPARTJIRIRIKOKUA2NEW ],

    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1NEW ]: [TABS.LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1NEW ],
    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2NEW ]: [TABS.LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2NEW ],

    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTJIRIRIKOKUA1 ]: [TABS.LOGA_BP2_BIGPARTJIRIRIKOKUA1 ],
    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTJIRIRIKOKUA2 ]: [TABS.LOGA_BP2_BIGPARTJIRIRIKOKUA2 ],

    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1 ]: [TABS.LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1 ],
    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2 ]: [TABS.LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2 ],

    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTTABLETA1 ]: [TABS.LOGA_BP2_BIGPARTTABLETA1 ],
    [MODULE_PATHS.APP_LOGA_BP2_BIGPARTTABLETA2]: [TABS.LOGA_BP2_BIGPARTTABLETA2],

    [MODULE_PATHS.APP_LOGA_EKB_PROGRESSSCREEN ]: [TABS.LOGA_EKB_PROGRESSSCREEN ],
    [MODULE_PATHS.APP_LOGA_EKB_PROGRESS ]: [TABS.LOGA_EKB_PROGRESS ],
    [MODULE_PATHS.APP_LOGA_EKB_PROGRESSDETAILS ]: [TABS.LOGA_EKB_PROGRESSDETAILS ],
    [MODULE_PATHS.APP_LOGA_EKB_EKANBAN ]: [TABS.LOGA_EKB_EKANBAN ],
    [MODULE_PATHS.APP_LOGA_EKB_EKANBANPROGRESSSCREENA1 ]: [TABS.LOGA_EKB_EKANBANPROGRESSSCREENA1 ],
    [MODULE_PATHS.APP_LOGA_EKB_EKANBANPROGRESSSCREENA2 ]: [TABS.LOGA_EKB_EKANBANPROGRESSSCREENA2 ],

    [MODULE_PATHS.APP_LOGA_BARSCANINFO ]: [TABS.LOGA_BARSCANINFO ],
    [MODULE_PATHS.APP_LOGA_PCS_STOCK ]: [TABS.LOGA_PCS_STOCK ],

    [MODULE_PATHS.APP_LOGA_SPS_STOCK ]: [TABS.LOGA_SPS_STOCK ],

//Lgw Mwh
    [MODULE_PATHS.APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTSTATUS]: [TABS.LGW_MWH_LOGW_ADO_CALLINGLIGHTSTATUS],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTW1]: [TABS.LGW_MWH_LOGW_ADO_CALLINGLIGHTW1],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTW2]: [TABS.LGW_MWH_LOGW_ADO_CALLINGLIGHTW2],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTW3]: [TABS.LGW_MWH_LOGW_ADO_CALLINGLIGHTW3],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_ADO_CALLINGLIGHTIP]: [TABS.LGW_MWH_LOGW_ADO_CALLINGLIGHTIP],

    [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_MWHSMALLPART]: [TABS.LGW_MWH_LOGW_MWH_MWHSMALLPART],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_MWHBIGPART]: [TABS.LGW_MWH_LOGW_MWH_MWHBIGPART],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_STOCKATWH]: [TABS.LGW_MWH_LOGW_MWH_STOCKATWH],
    // [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_MODULECALLING]: [TABS.LGW_MWH_LOGW_MWH_MODULECALLING],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_ROBBINGLANE]: [TABS.LGW_MWH_LOGW_MWH_ROBBINGLANE],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_CASEDATA]: [TABS.LGW_MWH_LOGW_MWH_CASEDATA],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_CONTLIST]: [TABS.LGW_MWH_LOGW_MWH_CONTLIST],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_MWH_PARTDATA]: [TABS.LGW_MWH_LOGW_MWH_PARTDATA],

    [MODULE_PATHS.APP_LGW_MWH_LOGW_PUP_LOTUNPACKINGW1]: [TABS.LGW_MWH_LOGW_PUP_LOTUNPACKINGW1],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PUP_LOTUNPACKINGW2]: [TABS.LGW_MWH_LOGW_PUP_LOTUNPACKINGW2],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PUP_LOTUNPACKINGW3]: [TABS.LGW_MWH_LOGW_PUP_LOTUNPACKINGW3],

    [MODULE_PATHS.APP_LGW_MWH_LOGW_LUP_LOTUPPLAN]: [TABS.LGW_MWH_LOGW_LUP_LOTUPPLAN],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_LUP_CONTMODULE]: [TABS.LGW_MWH_LOGW_LUP_CONTMODULE],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PUP_LOTMAKINGTABLET]: [TABS.LGW_MWH_LOGW_PUP_LOTMAKINGTABLET],

    [MODULE_PATHS.APP_LGW_MWH_LOGW_DVN_CONTLIST]: [TABS.LGW_MWH_LOGW_DVN_CONTLIST],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_DVN_DEVANNINGSCREEN]: [TABS.LGW_MWH_LOGW_DVN_DEVANNINGSCREEN],

    [MODULE_PATHS.APP_LGW_MWH_LOGW_PUP_PXPUPPLAN]: [TABS.LGW_MWH_LOGW_PUP_PXPUPPLAN],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PUP_MODULEUNPACKINGANDON]: [TABS.LGW_MWH_LOGW_PUP_MODULEUNPACKINGANDON],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PUP_PXPUPPLANBASE]: [TABS.LGW_MWH_LOGW_PUP_PXPUPPLANBASE],

    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGPROGRESS]: [TABS.LGW_MWH_LOGW_PIK_PICKINGPROGRESS],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGTABLETUBW1]: [TABS.LGW_MWH_LOGW_PIK_PICKINGTABLETUBW1],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGTABLETSMW1]: [TABS.LGW_MWH_LOGW_PIK_PICKINGTABLETSMW1],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGTABLETUBW2]: [TABS.LGW_MWH_LOGW_PIK_PICKINGTABLETUBW2],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGTABLETSMW2]: [TABS.LGW_MWH_LOGW_PIK_PICKINGTABLETSMW2],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGTABLETUBW3]: [TABS.LGW_MWH_LOGW_PIK_PICKINGTABLETUBW3],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGTABLETSMW3]: [TABS.LGW_MWH_LOGW_PIK_PICKINGTABLETSMW3],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGMONITORW1]: [TABS.LGW_MWH_LOGW_PIK_PICKINGMONITORW1],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGMONITORW2]: [TABS.LGW_MWH_LOGW_PIK_PICKINGMONITORW2],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGMONITORW3]: [TABS.LGW_MWH_LOGW_PIK_PICKINGMONITORW3],
    [MODULE_PATHS.APP_LGW_MWH_LOGW_PIK_PICKINGSIGNAL]: [TABS.LGW_MWH_LOGW_PIK_PICKINGSIGNAL],

    [MODULE_PATHS.APP_MST_LOGW_ADO_CALLINGLIGHTSTATUS]: [TABS.MST_LOGW_ADO_CALLINGLIGHTSTATUS],

/*Painting Andon*/
    [MODULE_PATHS.APP_PTA_ADO_CCRMONITOR ]: [TABS.PTA_ADO_CCRMONITOR ],
    [MODULE_PATHS.APP_PTA_ADO_SCANINFO ]: [TABS.PTA_ADO_SCANINFO ],
    [MODULE_PATHS.APP_PTA_ADO_PAINTINGDATA ]: [TABS.PTA_ADO_PAINTINGDATA ],
    [MODULE_PATHS.APP_PTA_ADO_PAINTINGPROGRESS ]: [TABS.PTA_ADO_PAINTINGPROGRESS ],
    [MODULE_PATHS.APP_PTA_ADO_LINEEFFICIENCY]: [TABS.PTA_ADO_LINEEFFICIENCY],
    [MODULE_PATHS.APP_PTA_ADO_LINEEFFICIENCYDETAILS ]: [TABS.PTA_ADO_LINEEFFICIENCYDETAILS ],
    [MODULE_PATHS.APP_PTA_ADO_LINEREALTIMECONTROL ]: [TABS.PTA_ADO_LINEREALTIMECONTROL ],
    [MODULE_PATHS.APP_PTA_ADO_TOTALDELAY ]: [TABS.PTA_ADO_TOTALDELAY ],
    [MODULE_PATHS.APP_PTA_ADO_BUMPER ]: [TABS.PTA_ADO_BUMPER ],
    [MODULE_PATHS.APP_PTA_ADO_DELAYCONTROLSCREEN]: [TABS.PTA_ADO_DELAYCONTROLSCREEN],
    [MODULE_PATHS.APP_PTA_ADO_BUMPERCLRINDICATOR ]: [TABS.PTA_ADO_BUMPERCLRINDICATOR ],
    [MODULE_PATHS.APP_PTA_ADO_NEXTEDIN ]: [TABS.PTA_ADO_NEXTEDIN ],
    [MODULE_PATHS.APP_PTA_ADO_BUMPERGETDATASMALLSUBASSY ]: [TABS.PTA_ADO_BUMPERGETDATASMALLSUBASSY ],
    [MODULE_PATHS.APP_PTA_ADO_BUMPERIN ]: [TABS.PTA_ADO_BUMPERIN ],
    [MODULE_PATHS.APP_PTA_ADO_BUMPERSUBASSYA1 ]: [TABS.PTA_ADO_BUMPERSUBASSYA1 ],
    [MODULE_PATHS.APP_PTA_ADO_BUMPERSUBASSYA2 ]: [TABS.PTA_ADO_BUMPERSUBASSYA2 ],

//PLAN
    [MODULE_PATHS.APP_PLA_CCR_PRODUCTIONPLAN ]: [TABS.PLA_CCR_PRODUCTIONPLAN ],

//Welding Andon
    [MODULE_PATHS.APP_WEL_ADO_PROCESSINSTRUCTION ]: [TABS.WEL_ADO_PROCESSINSTRUCTION ],
    [MODULE_PATHS.APP_WEL_ADO_WELDINGPLAN ]: [TABS.WEL_ADO_WELDINGPLAN ],
    [MODULE_PATHS.APP_WEL_ADO_WELDINGPROGRESS ]: [TABS.WEL_ADO_WELDINGPROGRESS ],
    [MODULE_PATHS.APP_WEL_ADO_PUNCHQUEUE ]: [TABS.WEL_ADO_PUNCHQUEUE ],
    [MODULE_PATHS.APP_WEL_ADO_WELDINGSIGNAL ]: [TABS.WEL_ADO_WELDINGSIGNAL ],
    [MODULE_PATHS.APP_WEL_ADO_PUNCHQUEUEINDICATOR ]: [TABS.WEL_ADO_PUNCHQUEUEINDICATOR ],

};
