export const TABS = {


/*ASSEMBLY*/
    //sps
    ASSY_SPS_ASSEMBLYDATASCREENA1: 'ASSY_SPS_ASSEMBLYDATASCREENA1',
    ASSY_SPS_ASSEMBLYDATASCREENA2: 'ASSY_SPS_ASSEMBLYDATASCREENA2',
    //ado
    ASSY_ADO_VEHICLEDETAILS: 'ASSY_ADO_VEHICLEDETAILS',
    ASSY_ADO_TOTALDELAYFINALASAKAI: 'ASSY_ADO_TOTALDELAYFINALASAKAI',
    ASSY_ADO_AINPLAN: 'ASSY_ADO_AINPLAN',
    ASSY_ADO_APLANSHIFTBASE: 'ASSY_ADO_APLANSHIFTBASE',
    ASSY_ADO_ASSEMBLYDATA: 'ASSY_ADO_ASSEMBLYDATA',

/*FRAME */
    FRM_ADO_FRAMEPLAN: 'FRM_ADO_FRAMEPLAN',
    FRM_ADO_FRAMEPROGRESS: 'FRM_ADO_FRAMEPROGRESS',
    FRM_ADO_FRAMEPLANA1: 'FRM_ADO_FRAMEPLANA1',
    FRM_ADO_FRAMEPLANBMPV: 'FRM_ADO_FRAMEPLANBMPV',



/* MASTER */
    /* MASTER - Working Pattern */
    MASTER_WORKING_PATTERN_SHOP  : 'MASTER_WORKING_PATTERN_SHOP',
    MASTER_WORKING_PATTERN_CALENDAR   : 'MASTER_WORKING_PATTERN_CALENDAR',
    MASTER_WORKING_PATTERN_SEASONMONTH   : 'MASTER_WORKING_PATTERN_SEASONMONTH',
    MASTER_WORKING_PATTERN_PATTERNH   : 'MASTER_WORKING_PATTERN_PATTERNH',
    MASTER_WORKING_PATTERN_WORKINGTIME : 'MASTER_WORKING_PATTERN_WORKINGTIME',
    MASTER_WORKING_PATTERN_WORKINGTYPE  : 'MASTER_WORKING_PATTERN_WORKINGTYPE',
    MASTER_WORKING_PATTERN_DAILYWORKINGTIME : 'MASTER_WORKING_PATTERN_DAILYWORKINGTIME',
    MASTER_WORKING_PATTERN_PATTERND   : 'MASTER_WORKING_PATTERN_PATTERND',
    MASTER_WORKING_PATTERN_WEEK   : 'MASTER_WORKING_PATTERN_WEEK',

    // MASTER - WELDING
    MASTER_WELDING_PROCESS  : 'MASTER_WELDING_PROCESS',

    /* MASTER - COMMON*/
    // MASTER_COMMON_LOOKUP  : 'MASTER_COMMON_LOOKUP',
    // APP_MASTER_COMMON_TAKTTIME  : 'APP_MASTER_COMMON_TAKTTIME',
    // APP_MASTER_COMMON_MODEL  : 'APP_MASTER_COMMON_MODEL',
    // APP_MASTER_COMMON_COLOR : 'APP_MASTER_COMMON_COLOR',
    MASTER_COMMON_LOOKUP2  : 'MASTER_COMMON_LOOKUP2',


    // MASTER - LOGA
    MASTER_LOGA_PLCSIGNAL : 'MASTER_LOGA_PLCSIGNAL',
    MASTER_LOGA_TRIP : 'MASTER_LOGA_TRIP',
    MASTER_LOGA_BP2PARTLIST : 'MASTER_LOGA_BP2PARTLIST',
    MASTER_LOGA_BP2PROCESS : 'MASTER_LOGA_BP2PROCESS',
    MASTER_LOGA_BP2ECAR : 'MASTER_LOGA_BP2ECAR',
    MASTER_LOGA_BP2PARTLISTGRADE : 'MASTER_LOGA_BP2PARTLISTGRADE',
    MASTER_LOGA_EKBPARTLIST : 'MASTER_LOGA_EKBPARTLIST',
    MASTER_LOGA_EKBPARTLISTGRADE : 'MASTER_LOGA_EKBPARTLISTGRADE',
    MASTER_LOGA_EKBPROCESS  : 'MASTER_LOGA_EKBPROCESS',
    MASTER_LOGA_EKBUSER  : 'MASTER_LOGA_EKBUSER',
    MASTER_LOGA_BARPROCESS  : 'MASTER_LOGA_BARPROCESS',
    MASTER_LOGA_BARUSER  : 'MASTER_LOGA_BARUSER',
    MASTER_LOGA_SPSRACK  : 'MASTER_LOGA_SPSRACK',
    MASTER_LOGA_PCRACK  : 'MASTER_LOGA_PCRACK',

    //MASTER - PAINTING
    MASTER_PAINTING_PAINTINGPROCESS  : 'MASTER_PAINTING_PAINTINGPROCESS',
    MASTER_PAINTING_BMPPARTLIST  : 'MASTER_PAINTING_BMPPARTLIST',
    MASTER_PAINTING_BMPPARTTYPE : 'MASTER_PAINTING_BMPPARTTYPE',
    MASTER_PAINTING_INVENTORYSTD : 'MASTER_PAINTING_INVENTORYSTD',

    MASTER_FRAME_PROCESS : 'MASTER_FRAME_PROCESS',

    // MASTER - LOGW
    MASTER_LOGW_ECIPART : 'MASTER_LOGW_ECIPART',
    MASTER_LOGW_ECIPARTMODULE : 'MASTER_LOGW_ECIPARTMODULE',
    MASTER_LOGW_CONTDEVANNINGLT : 'MASTER_LOGW_CONTDEVANNINGLT',
    MASTER_LOGW_MODELGRADE : 'MASTER_LOGW_MODELGRADE',
    MASTER_LOGW_RENBANMODULE : 'MASTER_LOGW_RENBANMODULE',
    MASTER_LOGW_LAYOUTSETUP : 'MASTER_LOGW_LAYOUTSETUP',
    MASTER_LOGW_LAYOUT : 'MASTER_LOGW_LAYOUT',
    MASTER_LOGW_PLCSIGNAL : 'MASTER_LOGW_PLCSIGNAL',

    // MASTER - ROBBINGLANE
    MASTER_LOGW_ROBBINGLANE : 'MASTER_LOGW_ROBBINGLANE',
    MASTER_LOGW_SCREENCONFIG : 'MASTER_LOGW_SCREENCONFIG',

    // MASTER - PICKINGTABLET
    MASTER_LOGW_PICKINGTABLET : 'MASTER_LOGW_PICKINGTABLET',
    MASTER_LOGW_PICKINGTABLETSETUP : 'MASTER_LOGW_PICKINGTABLETSETUP',

    // MASTER - UNPACKINGPART
    MASTER_LOGW_UNPACKINGPART : 'MASTER_LOGW_UNPACKINGPART',

    //CALLINGTIGHT
    MASTER_LOGW_CALLINGLIGHT : 'MASTER_LOGW_CALLINGLIGHT',

/* INV */
    //INV_D125
    INV_D125_STOCK : 'INV_D125_STOCK',
    INV_D125_INVOUTLINEOFF : 'INV_D125_INVOUTLINEOFF',
    INV_D125_OUTWIPSTOCK : 'INV_D125_OUTWIPSTOCK',
    INV_D125_INDETAILS : 'INV_D125_INDETAILS',

    //INV_DMR
    INV_DMR_IMPORTBYCONT : 'INV_DMR_IMPORTBYCONT',

    //INV_PROC
    INV_PROC_PRODUCTIONMAPPING : 'INV_PROC_PRODUCTIONMAPPING',
/* INVENTORY*/
    INVENTORY_CKD_STOCKPART: 'INVENTORY_CKD_STOCKPART',
    INVENTORY_CKD_STOCKISSUSING: 'INVENTORY_CKD_STOCKISSUSING',
    INVENTORY_CKD_STOCKRECEIVING: 'INVENTORY_CKD_STOCKRECEIVING',
    INVENTORY_CKD_STOCKBALANCE: 'INVENTORY_CKD_STOCKBALANCE',

    INVENTORY_CKD_PHYSICALSTOCKPART: 'INVENTORY_CKD_PHYSICALSTOCKPART',
    INVENTORY_CKD_PHYSICALSTOCKRECEIVING: 'INVENTORY_CKD_PHYSICALSTOCKRECEIVING',
    INVENTORY_CKD_PHYSICALSTOCKISSUING: 'INVENTORY_CKD_PHYSICALSTOCKISSUING',
    INVENTORY_CKD_PHYSICALSTOCKPERIOD: 'INVENTORY_CKD_PHYSICALSTOCKPERIOD',

/*LogA */
    LOGA_LDS_LOTPLAN : 'LOGA_LDS_LOTPLAN ',
    LOGA_LDS_LOTDIRECTSUPPLYANDONA1 : 'LOGA_LDS_LOTDIRECTSUPPLYANDONA1 ',
    LOGA_LDS_LOTDIRECTSUPPLYANDONA2 : 'LOGA_LDS_LOTDIRECTSUPPLYANDONA2 ',
    LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA1 : 'LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA1 ',
    LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA2 : 'LOGA_LDS_LOTDIRECTSUPPLYJIRIRIKOKUA2 ',

    LOGA_BP2_PROGRESS : 'LOGA_BP2_PROGRESS ',
    LOGA_BP2_PXPUPPLAN : 'LOGA_BP2_PXPUPPLAN ',

    LOGA_BP2_BIGPARTPXPUP : 'LOGA_BP2_BIGPARTPXPUP ',

    LOGA_BP2_BIGPARTJIRIRIKOKUA1NEW : 'LOGA_BP2_BIGPARTJIRIRIKOKUA1NEW ',
    LOGA_BP2_BIGPARTJIRIRIKOKUA2NEW : 'LOGA_BP2_BIGPARTJIRIRIKOKUA2NEW ',

    LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1NEW : 'LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1NEW ',
    LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2NEW : 'LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2NEW ',

    LOGA_BP2_BIGPARTJIRIRIKOKUA1 : 'LOGA_BP2_BIGPARTJIRIRIKOKUA1 ',
    LOGA_BP2_BIGPARTJIRIRIKOKUA2 : 'LOGA_BP2_BIGPARTJIRIRIKOKUA2 ',

    LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1 : 'LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA1 ',
    LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2 : 'LOGA_BP2_BIGPARTDIRECTDELIVERYPROGRESSA2 ',

    LOGA_BP2_BIGPARTTABLETA1 : 'LOGA_BP2_BIGPARTTABLETA1 ',
    LOGA_BP2_BIGPARTTABLETA2: 'LOGA_BP2_BIGPARTTABLETA2',

    LOGA_EKB_PROGRESSSCREEN : 'LOGA_EKB_PROGRESSSCREEN ',
    LOGA_EKB_PROGRESS : 'LOGA_EKB_PROGRESS ',
    LOGA_EKB_PROGRESSDETAILS : 'LOGA_EKB_PROGRESSDETAILS ',
    LOGA_EKB_EKANBAN : 'LOGA_EKB_EKANBAN ',
    LOGA_EKB_EKANBANPROGRESSSCREENA1 : 'LOGA_EKB_EKANBANPROGRESSSCREENA1 ',
    LOGA_EKB_EKANBANPROGRESSSCREENA2 : 'LOGA_EKB_EKANBANPROGRESSSCREENA2 ',

    LOGA_BARSCANINFO : 'LOGA_BARSCANINFO ',
    LOGA_PCS_STOCK : 'LOGA_PCS_STOCK ',

    LOGA_SPS_STOCK : 'LOGA_SPS_STOCK ',

//Lgw Mwh
    LGW_MWH_LOGW_ADO_CALLINGLIGHTSTATUS: 'LGW_MWH_LOGW_ADO_CALLINGLIGHTSTATUS',
    LGW_MWH_LOGW_ADO_CALLINGLIGHTW1: 'LGW_MWH_LOGW_ADO_CALLINGLIGHTW1',
    LGW_MWH_LOGW_ADO_CALLINGLIGHTW2: 'LGW_MWH_LOGW_ADO_CALLINGLIGHTW2',
    LGW_MWH_LOGW_ADO_CALLINGLIGHTW3: 'LGW_MWH_LOGW_ADO_CALLINGLIGHTW3',
    LGW_MWH_LOGW_ADO_CALLINGLIGHTIP: 'LGW_MWH_LOGW_ADO_CALLINGLIGHTIP',

    LGW_MWH_LOGW_MWH_MWHSMALLPART: 'LGW_MWH_LOGW_MWH_MWHSMALLPART',
    LGW_MWH_LOGW_MWH_MWHBIGPART: 'LGW_MWH_LOGW_MWH_MWHBIGPART',
    LGW_MWH_LOGW_MWH_STOCKATWH: 'LGW_MWH_LOGW_MWH_STOCKATWH',
    LGW_MWH_LOGW_MWH_MODULECALLING: 'LGW_MWH_LOGW_MWH_MODULECALLING',
    LGW_MWH_LOGW_MWH_ROBBINGLANE: 'LGW_MWH_LOGW_MWH_ROBBINGLANE',
    LGW_MWH_LOGW_MWH_CASEDATA: 'LGW_MWH_LOGW_MWH_CASEDATA',
    LGW_MWH_LOGW_MWH_CONTLIST: 'LGW_MWH_LOGW_MWH_CONTLIST',
    LGW_MWH_LOGW_MWH_PARTDATA: 'LGW_MWH_LOGW_MWH_PARTDATA',

    LGW_MWH_LOGW_PUP_LOTUNPACKINGW1: 'LGW_MWH_LOGW_PUP_LOTUNPACKINGW1',
    LGW_MWH_LOGW_PUP_LOTUNPACKINGW2: 'LGW_MWH_LOGW_PUP_LOTUNPACKINGW2',
    LGW_MWH_LOGW_PUP_LOTUNPACKINGW3: 'LGW_MWH_LOGW_PUP_LOTUNPACKINGW3',

    LGW_MWH_LOGW_LUP_LOTUPPLAN: 'LGW_MWH_LOGW_LUP_LOTUPPLAN',
    LGW_MWH_LOGW_LUP_CONTMODULE: 'LGW_MWH_LOGW_LUP_CONTMODULE',
    LGW_MWH_LOGW_PUP_LOTMAKINGTABLET: 'LGW_MWH_LOGW_PUP_LOTMAKINGTABLET',

    LGW_MWH_LOGW_DVN_CONTLIST: 'LGW_MWH_LOGW_DVN_CONTLIST',
    LGW_MWH_LOGW_DVN_DEVANNINGSCREEN: 'LGW_MWH_LOGW_DVN_DEVANNINGSCREEN',

    LGW_MWH_LOGW_PUP_PXPUPPLAN: 'LGW_MWH_LOGW_PUP_PXPUPPLAN',
    LGW_MWH_LOGW_PUP_MODULEUNPACKINGANDON: 'LGW_MWH_LOGW_PUP_MODULEUNPACKINGANDON',
    LGW_MWH_LOGW_PUP_PXPUPPLANBASE: 'LGW_MWH_LOGW_PUP_PXPUPPLANBASE',

    LGW_MWH_LOGW_PIK_PICKINGPROGRESS: 'LGW_MWH_LOGW_PIK_PICKINGPROGRESS',
    LGW_MWH_LOGW_PIK_PICKINGTABLETUBW1: 'LGW_MWH_LOGW_PIK_PICKINGTABLETUBW1',
    LGW_MWH_LOGW_PIK_PICKINGTABLETSMW1: 'LGW_MWH_LOGW_PIK_PICKINGTABLETSMW1',
    LGW_MWH_LOGW_PIK_PICKINGTABLETUBW2: 'LGW_MWH_LOGW_PIK_PICKINGTABLETUBW2',
    LGW_MWH_LOGW_PIK_PICKINGTABLETSMW2: 'LGW_MWH_LOGW_PIK_PICKINGTABLETSMW2',
    LGW_MWH_LOGW_PIK_PICKINGTABLETUBW3: 'LGW_MWH_LOGW_PIK_PICKINGTABLETUBW3',
    LGW_MWH_LOGW_PIK_PICKINGTABLETSMW3: 'LGW_MWH_LOGW_PIK_PICKINGTABLETSMW3',
    LGW_MWH_LOGW_PIK_PICKINGMONITORW1: 'LGW_MWH_LOGW_PIK_PICKINGMONITORW1',
    LGW_MWH_LOGW_PIK_PICKINGMONITORW2: 'LGW_MWH_LOGW_PIK_PICKINGMONITORW2',
    LGW_MWH_LOGW_PIK_PICKINGMONITORW3: 'LGW_MWH_LOGW_PIK_PICKINGMONITORW3',
    LGW_MWH_LOGW_PIK_PICKINGSIGNAL: 'LGW_MWH_LOGW_PIK_PICKINGSIGNAL',
    MST_LOGW_ADO_CALLINGLIGHTSTATUS: 'MST_LOGW_ADO_CALLINGLIGHTSTATUS',


/*Painting Andon*/
    PTA_ADO_CCRMONITOR : 'PTA_ADO_CCRMONITOR ',
    PTA_ADO_SCANINFO : 'PTA_ADO_SCANINFO ',
    PTA_ADO_PAINTINGDATA : 'PTA_ADO_PAINTINGDATA ',
    PTA_ADO_PAINTINGPROGRESS : 'PTA_ADO_PAINTINGPROGRESS ',
    PTA_ADO_LINEEFFICIENCY: 'PTA_ADO_LINEEFFICIENCY',
    PTA_ADO_LINEEFFICIENCYDETAILS : 'PTA_ADO_LINEEFFICIENCYDETAILS ',
    PTA_ADO_LINEREALTIMECONTROL : 'PTA_ADO_LINEREALTIMECONTROL ',
    PTA_ADO_TOTALDELAY : 'PTA_ADO_TOTALDELAY ',
    PTA_ADO_BUMPER : 'PTA_ADO_BUMPER ',
    PTA_ADO_DELAYCONTROLSCREEN: 'PTA_ADO_DELAYCONTROLSCREEN',
    PTA_ADO_BUMPERCLRINDICATOR : 'PTA_ADO_BUMPERCLRINDICATOR ',
    PTA_ADO_NEXTEDIN : 'PTA_ADO_NEXTEDIN ',
    PTA_ADO_BUMPERGETDATASMALLSUBASSY : 'PTA_ADO_BUMPERGETDATASMALLSUBASSY ',
    PTA_ADO_BUMPERIN : 'PTA_ADO_BUMPERIN ',
    PTA_ADO_BUMPERSUBASSYA1 : 'PTA_ADO_BUMPERSUBASSYA1 ',
    PTA_ADO_BUMPERSUBASSYA2 : 'PTA_ADO_BUMPERSUBASSYA2 ',

//PLAN
    PLA_CCR_PRODUCTIONPLAN : 'PLA_CCR_PRODUCTIONPLAN ',

//Welding Andon
    WEL_ADO_PROCESSINSTRUCTION : 'WEL_ADO_PROCESSINSTRUCTION ',
    WEL_ADO_WELDINGPLAN : 'WEL_ADO_WELDINGPLAN ',
    WEL_ADO_WELDINGPROGRESS : 'WEL_ADO_WELDINGPROGRESS ',
    WEL_ADO_PUNCHQUEUE : 'WEL_ADO_PUNCHQUEUE ',
    WEL_ADO_WELDINGSIGNAL : 'WEL_ADO_WELDINGSIGNAL ',
    WEL_ADO_PUNCHQUEUEINDICATOR : 'WEL_ADO_PUNCHQUEUEINDICATOR ',

};
